In [22]:
import numpy as np
a = np.arange(1,10).reshape(3,3)
a[[0,2], 0:2]

array([[1, 2],
       [7, 8]])

In [157]:
## 파이썬 리스트를 사용하여 2~5번의 원소를 추출하고
## 추출된 하위 리스트의 첫 번째 항에 100을 할당한다
## 그리고 원본 리스트의 2번 항에 어떤 값이 있는지 조사
## 동일한 내용으로 Numpy 배열에도 적용하여 검사한다
a = np.arange(1,10)
b = [1,2,3,4,5,6,7,8,9]

print(a)
print(b)

list = a[2:5]
list[0] = 100

list2 = b[2:5]
list2[0] = 100
print(a)
print(list2)
a[0] = 100
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[[  1   2   3]
 [  4   5   6]
 [100 100 100]]
[100, 4, 5]
[[100 100 100]
 [  4   5   6]
 [100 100 100]]


In [46]:
## 1~25(포함)까지 5x5행렬(2차원 ndarray)을 생성하고 2번째 행만 추출하여 평균을 구하여 표시하고,
## 3번째 컬럼만 추출하여 평균을 구해서 표시해보세요.
## 3번째 행의 3,4,5번째 컬럼의 값을 합산하여 표시해보세요.
## 4번째 컬럼 전체의 분산(np.var(arr)) 구하기, 5번째 행 전체의 표준편차 구하기
a = np.arange(1,26).reshape(5,5)
slice1 = a[1,:]
slice2 = a[2,:]

print('2번째 행 평균:',slice1.mean())

print('3번째 행 평균:',slice2.mean())

print('3번째 행 3~5번 원소 합:',slice2[2:4].sum())

slice3 = a[:,3]
print('4번째 컬럼 전체의 분산:',np.var(slice3))
slice4 = a[4,:]
print('5번째 행 전체의 표준편차:',np.sqrt(np.var(slice4)))

2번째 행 평균: 8.0
3번째 행 평균: 13.0
3번째 행 3~5번 원소 합: 27
4번째 컬럼 전체의 분산: 50.0
5번째 행 전체의 표준편차: 1.4142135623730951


# Boolean Indexing 응용
zeros()를 사용하여 3x3행렬을 생성하고 가운데 컬럼의 값 중에서 2,3번째 행의 값을 1로 설정한다
이어서 0으로 설정된 값을 모두 5로 변경하고 화면에 표시

In [61]:
zArr = np.zeros([3,3])
zArr[1:3,1]=1
zArr[zArr==0]=5
print(zArr)

[[5. 5. 5.]
 [5. 1. 5.]
 [5. 1. 5.]]


<h1>#ravel 테스트</h1>
#2차원 행렬을 생성하고 ravel()을 사용하여 1차원으로 변경한 후에 1차원 배열의 원소를 몇개 수정하고
원본의 원소가 변경되었는지 확인한다

In [66]:
a = np.arange(1,10).reshape(3,3)
b = np.ravel(a)
b[3:5] = 99
print(a)

[[ 1  2  3]
 [99 99  6]
 [ 7  8  9]]


<h1>transpose</h1>
numpy를 사용하여 1~9까지의 1차원 배열을 생성하고 원본을 3x3행렬로 변경한다<br>
이 결과 행렬의 전치행렬을 구해서 표시한다

In [76]:
a = np.arange(1,10)
a.shape=[3,3]
print(a)
b = np.transpose(a)
b[1,1] = 99
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4 99  6]
 [ 7  8  9]]
[[ 1  4  7]
 [ 2 99  8]
 [ 3  6  9]]


# <h1>Array Manipulate</h1>
2차원(2x3) 임의의 정수(20이하) 배열(A)을 생성하고 2차원 (2x3) 0 배열(B)를 생성한다<br>
A,B를 수평으로 결합하여 생성된 C배열을 생성한다.<br>
C배열의 원소를 변경했을 때 원본 배열의 영향은?

In [155]:
A = np.random.randint(21,size=(2,3))
B = np.zeros([2,3])
C = np.hstack((A,B))
print(C,'\n')
C[0,[1,4]] = 99
C[C==0]=88
print(C,'\n')
print(np.hstack((A,B)))

[[ 7. 12. 13.  0.  0.  0.]
 [19. 11. 12.  0.  0.  0.]] 

[[ 7. 99. 13. 88. 99. 88.]
 [19. 11. 12. 88. 88. 88.]] 

[[ 7. 12. 13.  0.  0.  0.]
 [19. 11. 12.  0.  0.  0.]]


<h1>split, stack practice</h1>
3개의 행렬 생성 ==> [1,2,3], [4,5,6], [7,8,9]<br>
* 이들 행렬을 컬럼으로 사용하여 D 행렬 생성<br>
* 이들 행렬을 행으로 사용하여 E 행렬 생성<br>
* D,E 행렬을 수직으로 합쳐서 H 행렬 생성<br>
* D의 수직 합계, E의 수평 합계를 수평으로 합쳐서 I 행렬 생성<br>
* H행렬의 첫번째, 세번째 컬럼 수평합계 산출

In [223]:
arr = np.arange(1,10).reshape(3,3)
A,B,C = np.vsplit(arr,3) # 상하로 나뉘도록 3칸으로 쪼개기
A = np.ravel(A)   # 1차원 리스트로 전환
B = np.ravel(B)
C = np.ravel(C)
print('A행렬:',A,'\nB행렬:',B,'\nC행렬:',C)

D = np.column_stack((A,B,C))
E = np.row_stack((A,B,C))
print('---D행렬:\n',D,'\n\n---E행렬:\n',E)
H = np.vstack((D,E))
print('\n---H행렬:\n',H)
I = np.hstack((np.apply_along_axis(np.sum, axis=0, arr=D),np.apply_along_axis(np.sum, axis=1, arr=E)))
print('\n---I행렬:\n',I)
H1,H2,H3 = np.split(H,[1,2],axis=1)
print('\nH1행렬:\n',H1,'\nH2행렬:\n',H2,'\nH3행렬:\n',H3)
J = np.column_stack((H[:,0],H[:,2]))
print('\n---H행렬 첫 번째, 세 번째 컬럼 결합:\n',J)
print('\nH행렬의 첫 번째, 세 번째 컬럼 수평 합계 :',np.apply_along_axis(np.sum, axis=1, arr=J))

A행렬: [1 2 3] 
B행렬: [4 5 6] 
C행렬: [7 8 9]
---D행렬:
 [[1 4 7]
 [2 5 8]
 [3 6 9]] 

---E행렬:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

---H행렬:
 [[1 4 7]
 [2 5 8]
 [3 6 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]

---I행렬:
 [ 6 15 24  6 15 24]

H1행렬:
 [[1]
 [2]
 [3]
 [1]
 [4]
 [7]] 
H2행렬:
 [[4]
 [5]
 [6]
 [2]
 [5]
 [8]] 
H3행렬:
 [[7]
 [8]
 [9]
 [3]
 [6]
 [9]]

---H행렬 첫 번째, 세 번째 컬럼 결합:
 [[1 7]
 [2 8]
 [3 9]
 [1 3]
 [4 6]
 [7 9]]

H행렬의 첫 번째, 세 번째 컬럼 수평 합계 : [ 8 10 12  4 10 16]


In [229]:
a = np.array([1,2,3,4])
b = a.copy()
b[1]=99
print(a,type(a))
print(b)

[1 2 3 4] <class 'numpy.ndarray'>
[ 1 99  3  4]


<h1>Structured Array</h1>
번호, 이름, 나이, 급여액, 근무연수 3사람 분 데이터 만들어 화면에 출력

In [254]:
structured = np.array([(7,'Son',28,3000,6),(10,'Kane',27,3000,10),(20,'Ali',24,1500,8),(5,'Hojbjer',25,1800,1)],
                      dtype=[('num','int8'),('name','a20'),('age','int8'),('salary','int32'),('working year','int8')])

print(structured['name'])
print('최대급여와 최소급여 차 :', structured['salary'].max()-structured['salary'].min())
print(structured)

[b'Son' b'Kane' b'Ali' b'Hojbjer']
최대급여와 최소급여 차 : 1500
[( 7, b'Son', 28, 3000,  6) (10, b'Kane', 27, 3000, 10)
 (20, b'Ali', 24, 1500,  8) ( 5, b'Hojbjer', 25, 1800,  1)]
